version: '3.8'

services:
  ai-voice-agent:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/app
    volumes:
      - ../:/app
    env_file:
      - ../.env
