livekit:
  api_key: "${LIVEKIT_API_KEY}"
  api_secret: "${LIVEKIT_API_SECRET}"
  ws_url: "${LIVEKIT_WS_URL}"

room:
  default_timeout: 300
  max_participants: 10
  auto_subscribe: true

audio:
  codec: "opus"
  bitrate: 64000
  sample_rate: 48000
